version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - mongodata:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: adminuser
    #   MONGO_INITDB_ROOT_PASSWORD: secret
    env_file:
      - ./env/mongo.env
  backend:
    build: ./multi-01-starting-setup/backend
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    #   args:
    #     - some-arg: 1
    ports:
      - "80:80"
    volumes:
      - logs:/app/logs
      - ./multi-01-starting-setup/backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb

  # frontend:

volumes:
  mongodata:
  logs:
