version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - mongodata:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: adminuser
    #   MONGO_INITDB_ROOT_PASSWORD: secret
    env_file:
      - ./env/mongo.env
  # backend:
  # frontend:

volumes:
  mongodata:
